spring:
  profiles:
    include: oauth


  application:
    name: spring-remind

  security:
    user:
      name: admin
      password: 1234

  datasource:
    url: jdbc:h2:mem:testdb  # H2 인메모리 데이터베이스 사용
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
      database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  servlet:
    encoding:
      force: true